.TH "GTK VNC Viewer" 1
.SH NAME
GTK VNC Viewer \- Simple GTK tool to connect to VNC servers
.SH SYNOPSIS
.B gtkvncviewer
.SH DESCRIPTION
GTK VNC Viewer is a script that provides a GUI for connecting to VNC servers. It remembers the credentials of known servers, so connecting to a VNC server is just one double-click away. Servers are shown in an icon view.
.SH AUTHOR
Clement Lorteau <northern_lights@users.sourceforge.net>
.SH WEBSITE
http://launchpad.net/gtkvncviewer
.SH REPORTING BUGS
http://bugs.launchpad.net/gtkvncviewer/trunk/
.SH SEE ALSO
vncserver, xvncviewer, tightvncserver, xtightvncviewer
