.TH "Gtk VNC Viewer" 1
.SH NAME
gtkvncviewer \- Simple Gtk+ tool to connect to VNC servers
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Show a help message and exit.
.TP
\fB\-s\fR server, \fB\-\-server\fR=\fIserver\fR
If server is known by gtkvncviewer, immediately
connect to it.
.SH DESCRIPTION
Gtk VNC Viewer is a script that provides a GUI for connecting to VNC servers. It remembers the credentials of known servers, so connecting to a VNC server is just one double-click away. Servers are shown in an icon view.
.SH AUTHORS
2008 - Clement Lorteau <northern_lights@users.sourceforge.net>
2012 - Christoph Mende <mende.christoph@gmail.com>
.SH WEBSITE
http://cmende.scmpc.org/gtkvncviewer
.SH REPORTING BUGS
Please report bugs on https://github.com/cmende/gtkvncviewer/issues
